### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by jpheos** [kuartz-org/filterable_lib#1]
In the readme, it's mentionned to copy this files:

`app/javascript/controllers/filterable_controller.js`

`app/javascript/controllers/filterable_sort_controller.js`

`app/controllers/filterable/filters_controller.rb`

But they don't exist in the project?
Maybe we forgot to add them during commit?

**Comment by guillaumecabanel** [comment]
thanks @jpheos , I've added the missing files ;)
